// <auto-generated />
using System;
using BannerShop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BannerShop.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BannerShopDbContext))]
    partial class BannerShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BannerShop.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("NO");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.AiCreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("IX_AiCreditTransactions_ReferenceId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AiCreditTransactions_UserId");

                    b.ToTable("AiCreditTransactions");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComputedWidthCm")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PreviewStoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RotationDegrees")
                        .HasColumnType("int");

                    b.Property<int>("SelectedHeightCm")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_BannerDesigns_IpAddress");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_BannerDesigns_UserId_CreatedAt");

                    b.ToTable("BannerDesigns");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CroppedStoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DesignRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DesignRequestId")
                        .HasDatabaseName("IX_BannerGenerations_DesignRequestId");

                    b.ToTable("BannerGenerations");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("FixedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("HeightCm")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCustomHeight")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCustomWidth")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("WidthCm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("BannerSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeightCm = 150,
                            IsActive = true,
                            IsCustomHeight = false,
                            IsCustomWidth = false,
                            MaterialId = 1,
                            Name = "300 × 150 cm",
                            SortOrder = 1,
                            WidthCm = 300
                        },
                        new
                        {
                            Id = 2,
                            HeightCm = 150,
                            IsActive = true,
                            IsCustomHeight = false,
                            IsCustomWidth = false,
                            MaterialId = 1,
                            Name = "350 × 150 cm",
                            SortOrder = 2,
                            WidthCm = 350
                        },
                        new
                        {
                            Id = 3,
                            HeightCm = 150,
                            IsActive = true,
                            IsCustomHeight = false,
                            IsCustomWidth = false,
                            MaterialId = 1,
                            Name = "400 × 150 cm",
                            SortOrder = 3,
                            WidthCm = 400
                        },
                        new
                        {
                            Id = 4,
                            HeightCm = 150,
                            IsActive = true,
                            IsCustomHeight = false,
                            IsCustomWidth = false,
                            MaterialId = 1,
                            Name = "450 × 150 cm",
                            SortOrder = 4,
                            WidthCm = 450
                        },
                        new
                        {
                            Id = 5,
                            HeightCm = 150,
                            IsActive = true,
                            IsCustomHeight = false,
                            IsCustomWidth = false,
                            MaterialId = 1,
                            Name = "500 × 150 cm",
                            SortOrder = 5,
                            WidthCm = 500
                        },
                        new
                        {
                            Id = 6,
                            HeightCm = 150,
                            IsActive = true,
                            IsCustomHeight = false,
                            IsCustomWidth = true,
                            MaterialId = 1,
                            Name = "Valgfri bredde × 150 cm",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            FixedPrice = 699m,
                            HeightCm = 180,
                            IsActive = true,
                            IsCustomHeight = false,
                            IsCustomWidth = false,
                            MaterialId = 2,
                            Name = "300 × 180 cm",
                            SortOrder = 7,
                            WidthCm = 300
                        });
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameNb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("BannerTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Birthday",
                            NameEn = "Birthday",
                            NameNb = "Bursdag",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 8,
                            Category = "Baptism",
                            NameEn = "Baptism",
                            NameNb = "Dåp",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Confirmation",
                            NameEn = "Confirmation",
                            NameNb = "Konfirmasjon",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            Category = "Wedding",
                            NameEn = "Wedding",
                            NameNb = "Bryllup",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 4,
                            Category = "Anniversary",
                            NameEn = "Anniversary",
                            NameNb = "Jubileum",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Christmas",
                            NameEn = "Christmas party",
                            NameNb = "Julefeiring",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = 6,
                            Category = "NewYear",
                            NameEn = "New Year's party",
                            NameNb = "Nyttårsfeiring",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = 7,
                            Category = "Other",
                            NameEn = "Other occasion",
                            NameNb = "Annen feiring",
                            SortOrder = 70
                        });
                });

            modelBuilder.Entity("BannerShop.Core.Entities.DesignRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiPreviewPath")
                        .HasColumnType("longtext");

                    b.Property<string>("AiResultStoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("16:9");

                    b.Property<decimal>("BannerPriceNok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("BannerSizeId")
                        .HasColumnType("int");

                    b.Property<int>("BannerTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CurrentGenerationId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomBannerWidthCm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CustomerApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesignerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DesignerPreviewPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("FinalBannerDesignId")
                        .HasColumnType("int");

                    b.Property<string>("FinalCroppedStoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("nb");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonAge")
                        .HasColumnType("int");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PriceNok")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegenerationsRemaining")
                        .HasColumnType("int");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ThemeDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UploadedPhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BannerTemplateId");

                    b.HasIndex("CurrentGenerationId");

                    b.HasIndex("FinalBannerDesignId");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_DesignRequests_IpAddress");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_DesignRequests_OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("StripePaymentIntentId");

                    b.HasIndex("UserId");

                    b.ToTable("DesignRequests");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.DesignRequestRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerComment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DesignRequestId")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesignRequestId");

                    b.ToTable("DesignRequestRevisions");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.IpAiUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_IpAiUsages_IpAddress");

                    b.ToTable("IpAiUsages");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxBannerWidthCm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PricePerSqm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("WeightGsm")
                        .HasColumnType("int");

                    b.Property<int>("WidthCm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxBannerWidthCm = 160,
                            Name = "400g Frontlit Banner (160cm)",
                            PricePerSqm = 180m,
                            WeightGsm = 400,
                            WidthCm = 160
                        },
                        new
                        {
                            Id = 2,
                            AvailableFrom = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxBannerWidthCm = 180,
                            Name = "680g Heavy Duty Banner (180cm)",
                            PricePerSqm = 140m,
                            WeightGsm = 680,
                            WidthCm = 180
                        });
                });

            modelBuilder.Entity("BannerShop.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AiActivationFeeNok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExpressFeeNok")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte>("OrderState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<byte>("OrderType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("PackingMode")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingCostNok")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("TotalNok")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaSqm")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int?>("BannerDesignId")
                        .HasColumnType("int");

                    b.Property<int?>("BannerSizeId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomWidthCm")
                        .HasColumnType("int");

                    b.Property<int?>("DesignRequestId")
                        .HasColumnType("int");

                    b.Property<int>("EyeletCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("EyeletFeeNok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("EyeletOption")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("None");

                    b.Property<int>("HeightCm")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotalNok")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceNok")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BannerDesignId");

                    b.HasIndex("BannerSizeId");

                    b.HasIndex("DesignRequestId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.PricingParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PricingParameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "NOK per m² for standard banner material (400g)",
                            Key = "base_price_per_sqm",
                            Name = "Basispris per kvadratmeter",
                            Value = 180m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laveste pris for et enkelt banner (NOK)",
                            Key = "minimum_price",
                            Name = "Minimumspris",
                            Value = 399m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ekstra kostnad for valgfri bredde (NOK)",
                            Key = "custom_width_surcharge",
                            Name = "Tillegg valgfri bredde",
                            Value = 150m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pris per malje (NOK). Tilvalg per banner — ikke inkludert i basispris.",
                            Key = "eyelet_price_nok",
                            Name = "Maljepris (per stk)",
                            Value = 15m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tillegg for express produksjon (3 dager) i NOK",
                            Key = "express_fee",
                            Name = "Express produksjonstillegg",
                            Value = 500m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Estimert diameter på rullet banner-tube for forsendelse (cm)",
                            Key = "shipping_tube_diameter_cm",
                            Name = "Forsendelse: rull-diameter (cm)",
                            Value = 15m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Vekt av emballasje (tube, lokk, etiketter) i gram",
                            Key = "shipping_packaging_weight_g",
                            Name = "Forsendelse: emballasjevekt (g)",
                            Value = 500m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Maks tube-lengde transportør aksepterer (cm) — Bring Servicepakke",
                            Key = "shipping_max_length_cm",
                            Name = "Forsendelse: maks lengde (cm)",
                            Value = 240m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Produksjons- og leveringstid for standard ordre (dager fra bestilling)",
                            Key = "standard_lead_time_days",
                            Name = "Standard leveringstid (dager)",
                            Value = 14m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Produksjonstid for express-ordre (dager fra bestilling, før forsendelse)",
                            Key = "express_lead_time_days",
                            Name = "Express leveringstid (dager)",
                            Value = 3m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Pris for liten kreditpakke med AI forslag (NOK)",
                            Key = "ai_credit_pack_price_nok",
                            Name = "AI kreditpakke liten pris (NOK)",
                            Value = 29m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Antall AI genererings-kreditter per liten kreditpakke",
                            Key = "ai_credit_pack_count",
                            Name = "AI kreditpakke liten antall",
                            Value = 5m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Obligatorisk AI aktiveringsgebyr ved bestilling av banner med AI design (NOK)",
                            Key = "ai_banner_activation_fee_nok",
                            Name = "AI aktiveringsgebyr (NOK)",
                            Value = 95m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Antall AI kreditter som gis når AI aktiveringsgebyret er betalt",
                            Key = "ai_banner_activation_credits",
                            Name = "AI kreditter ved bestilling",
                            Value = 20m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Pris for stor kreditpakke med AI forslag (NOK)",
                            Key = "ai_credit_pack_large_price_nok",
                            Name = "AI kreditpakke stor pris (NOK)",
                            Value = 95m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Antall AI genererings-kreditter per stor kreditpakke",
                            Key = "ai_credit_pack_large_count",
                            Name = "AI kreditpakke stor antall",
                            Value = 20m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Overlapp i cm mellom panel ved sammenliming av brede banner. Bestemmer pris-multiplikator (×2, ×3, …) når bestilt bredde overstiger materialets maks bredde.",
                            Key = "banner_panel_overlap_cm",
                            Name = "Panel-overlapp (cm)",
                            Value = 5m
                        });
                });

            modelBuilder.Entity("BannerShop.Core.Entities.ProductionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("ProductionStatuses");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.ShipmentTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EstimatedArrival")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TrackingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ShipmentTrackings");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSensitive = true,
                            Key = "openai_api_key",
                            Label = "OpenAI API Key",
                            Value = ""
                        },
                        new
                        {
                            Id = 2,
                            IsSensitive = false,
                            Key = "openai_image_model",
                            Label = "OpenAI Image Model (blank = use config default)",
                            Value = ""
                        },
                        new
                        {
                            Id = 3,
                            IsSensitive = false,
                            Key = "openai_image_quality",
                            Label = "OpenAI Image Quality (blank = use config default; allowed: low, medium, high, auto)",
                            Value = ""
                        });
                });

            modelBuilder.Entity("BannerShop.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiCreditsRemaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("HasUsedFreeAiGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.Address", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.AiCreditTransaction", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.User", "User")
                        .WithMany("AiCreditTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerDesign", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerGeneration", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.DesignRequest", "DesignRequest")
                        .WithMany("Generations")
                        .HasForeignKey("DesignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignRequest");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerSize", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.Material", "Material")
                        .WithMany("BannerSizes")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.DesignRequest", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.BannerTemplate", "BannerTemplate")
                        .WithMany()
                        .HasForeignKey("BannerTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BannerShop.Core.Entities.BannerGeneration", "CurrentGeneration")
                        .WithMany()
                        .HasForeignKey("CurrentGenerationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BannerShop.Core.Entities.BannerDesign", "FinalBannerDesign")
                        .WithMany()
                        .HasForeignKey("FinalBannerDesignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BannerShop.Core.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BannerShop.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BannerTemplate");

                    b.Navigation("CurrentGeneration");

                    b.Navigation("FinalBannerDesign");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.DesignRequestRevision", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.DesignRequest", "DesignRequest")
                        .WithMany("Revisions")
                        .HasForeignKey("DesignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignRequest");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.Order", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.Address", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BannerShop.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.BannerDesign", "BannerDesign")
                        .WithMany()
                        .HasForeignKey("BannerDesignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BannerShop.Core.Entities.BannerSize", "BannerSize")
                        .WithMany("OrderItems")
                        .HasForeignKey("BannerSizeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BannerShop.Core.Entities.DesignRequest", "DesignRequest")
                        .WithMany()
                        .HasForeignKey("DesignRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BannerShop.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannerDesign");

                    b.Navigation("BannerSize");

                    b.Navigation("DesignRequest");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.ProductionStatus", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.OrderItem", "OrderItem")
                        .WithMany("ProductionStatuses")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.ShipmentTracking", b =>
                {
                    b.HasOne("BannerShop.Core.Entities.Order", "Order")
                        .WithOne("ShipmentTracking")
                        .HasForeignKey("BannerShop.Core.Entities.ShipmentTracking", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.BannerSize", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.DesignRequest", b =>
                {
                    b.Navigation("Generations");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.Material", b =>
                {
                    b.Navigation("BannerSizes");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ShipmentTracking");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.OrderItem", b =>
                {
                    b.Navigation("ProductionStatuses");
                });

            modelBuilder.Entity("BannerShop.Core.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AiCreditTransactions");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
